In [10]:
import sys
print(sys.version)
print(sys.prefix)

3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)]
c:\Users\OliverClancy\AppData\Local\Programs\Python\Python311


In [87]:
import numpy as np
import csv

with open('AAPL-2017.csv', newline='') as f:
    reader = csv.DictReader(f)
    prices2017 = np.empty((0,6), dtype=np.double)
    for row in reader:
        data = np.array([[row['Open'], row['High'], row['Low'], row['Close'], row['Adj Close'], row['Volume']]], dtype=np.double)
        prices2017 = np.append(prices2017, data,axis=0)

with open('AAPL-2016.csv', newline='') as f:
    reader = csv.DictReader(f)
    prices2016 = np.empty((0,6), dtype=np.double)
    for row in reader:
        data = np.array([[row['Open'], row['High'], row['Low'],  row['Close'],row['Adj Close'], row['Volume']]], dtype=np.double)
        prices2016 = np.append(prices2016, data,axis=0)



In [65]:

type(prices2016[0])
np.set_printoptions(formatter={'float': '{: 6.2f}'.format})


In [77]:
sum2016 = prices2016.sum(axis=0, dtype=np.double)
sum2017 = prices2017[:-1].sum(axis=0, dtype=np.double)
change = sum2017 - sum2016
print (type(sum2016))
print(type(change))
print(change)


<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[ 11488.29  11498.99  11454.06  11491.43  11758.32 -2850453900.00]


In [78]:
print(prices2017[:-1]-prices2016)

UFuncTypeError: ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> None

In [89]:
combined_years = np.concatenate([prices2016,prices2017])
print(type(combined_years[0][0]))
combined_years.sum(axis=0, dtype=np.double)

<class 'numpy.float64'>


array([ 63864.53,  64336.26,  63419.52,  63915.98,  62276.48,
        16445421900.00])

In [ ]:
np.set_printoptions(formatter={'float': '{: 6.2f}'.format})
np.savetxt("combined_years.csv",combined_years)

np.set_printoptions()

In [90]:
projection = combined_years[:, [0, 3]]
print(projection[:5])
result = projection[:5] * [[1.2,1.3]]

print(result[:5])

[[ 102.61  105.35]
 [ 105.75  102.71]
 [ 100.56  100.70]
 [ 98.68  96.45]
 [ 98.55  96.96]]
[[ 123.13  136.95]
 [ 126.90  133.52]
 [ 120.67  130.91]
 [ 118.42  125.38]
 [ 118.26  126.05]]
